## k-nearest neighbor classification  with iris dataset

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/wheat kernels.csv')
df.sample(10)

A      P       C     LK     WK  A_Coef    LKG  target
15   14.59  14.28  0.8993  5.351  3.333   4.185  4.781       0
74   16.82  15.51  0.8786  6.017  3.486   4.004  5.841       1
133  16.16  15.33  0.8644  5.845  3.395   4.266  5.795       1
136  17.36  15.76  0.8785  6.145  3.574   3.526  5.971       1
19   12.72  13.57  0.8686  5.226  3.049   4.102  4.914       0
34   15.05  14.68  0.8779  5.712  3.328   2.129  5.360       0
84   19.51  16.71  0.8780  6.366  3.801   2.962  6.185       1
171  11.55  13.10  0.8455  5.167  2.845   6.715  4.956       2
135  15.38  14.66  0.8990  5.477  3.465   3.600  5.439       1
38   14.80  14.52  0.8823  5.656  3.288   3.112  5.309       0

In [ ]:
df.target.value_counts()
#df.species.value_counts() # counting the lable class

2    70
1    70
0    70
Name: target, dtype: int64

In [ ]:
df.columns # feature all

Index(['A', 'P', 'C', 'LK', 'WK', 'A_Coef', 'LKG', 'target'], dtype='object')

In [ ]:
df.info() # target object label data 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       210 non-null    float64
 1   P       210 non-null    float64
 2   C       210 non-null    float64
 3   LK      210 non-null    float64
 4   WK      210 non-null    float64
 5   A_Coef  210 non-null    float64
 6   LKG     210 non-null    float64
 7   target  210 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.2 KB


# Scikit-learn: KNeighborsClassifier

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
cols=['A', 'P', 'C', 'LK', 'WK', 'A_Coef', 'LKG'] # featrue for classification

In [ ]:
X=df[cols]
y=df['target']

In [ ]:
test_size=0.2  
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=test_size, 
                                                    random_state=7)

In [ ]:
import numpy as np
error_rate = []

# Calculating error for K values between 1 and 10
for i in range(1, 11):
    model_knn = KNeighborsClassifier(n_neighbors=i)
    model_knn.fit(X_train, y_train)
    pred_i =  model_knn.predict(X_train)
    error_rate.append(np.mean(pred_i != y_train))


In [ ]:
error_rate # k=1 to k=10

[0.0,
 0.03571428571428571,
 0.047619047619047616,
 0.08928571428571429,
 0.09523809523809523,
 0.08928571428571429,
 0.09523809523809523,
 0.08333333333333333,
 0.09523809523809523,
 0.10714285714285714]

In [ ]:
model = KNeighborsClassifier(n_neighbors=9) #n_neighbors=9 error_rate 0.0083
model 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=9, p=2,
                     weights='uniform')

In [ ]:
model.fit(X_train, y_train) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=9, p=2,
                     weights='uniform')

In [ ]:
X_test

A      P       C     LK     WK  A_Coef    LKG
78   18.94  16.49  0.8750  6.445  3.639  5.0640  6.362
65   12.88  13.50  0.8879  5.139  3.119  2.3520  4.607
94   18.36  16.52  0.8452  6.666  3.485  4.9330  6.448
22   15.88  14.90  0.8988  5.618  3.507  0.7651  5.091
63   13.22  13.84  0.8680  5.395  3.070  4.1570  5.088
46   15.36  14.76  0.8861  5.701  3.393  1.3670  5.132
96   19.31  16.59  0.8815  6.341  3.810  3.4770  6.238
11   14.03  14.16  0.8796  5.438  3.201  1.7170  5.001
2    14.29  14.09  0.9050  5.291  3.337  2.6990  4.825
155  11.19  13.05  0.8253  5.250  2.675  5.8130  5.219
24   15.01  14.76  0.8657  5.789  3.245  1.7910  5.001
101  17.99  15.86  0.8992  5.890  3.694  2.0680  5.837
95   16.87  15.65  0.8648  6.139  3.463  3.6960  5.967
74   16.82  15.51  0.8786  6.017  3.486  4.0040  5.841
114  20.97  17.25  0.8859  6.563  3.991  4.6770  6.316
160  12.54  13.67  0.8425  5.451  2.879  3.0820  5.491
99   18.72  16.34  0.8810  6.219  3.684  2.1880  6.097
82   20.20  16.89  0.8894  6.285  3.864  5.1730  6.187
84   19.51  16.71  0.8780  6.366  3.801  2.9620  6.185
108  19.94  16.92  0.8752  6.675  3.763  3.2520  6.550
169  11.24  13.00  0.8359  5.090  2.715  3.5210  5.088
162  12.05  13.41  0.8416  5.267  2.847  4.9880  5.046
85   18.27  16.09  0.8870  6.173  3.651  2.4430  6.197
188  11.23  12.82  0.8594  5.089  2.821  7.5240  4.957
116  18.96  16.20  0.9077  6.051  3.897  4.3340  5.750
150  11.83  13.23  0.8496  5.263  2.840  5.1950  5.307
193  10.82  12.83  0.8256  5.180  2.630  4.8530  5.089
133  16.16  15.33  0.8644  5.845  3.395  4.2660  5.795
98   18.17  16.26  0.8637  6.271  3.512  2.8530  6.273
168  11.35  13.12  0.8291  5.176  2.668  4.3370  5.132
207  13.20  13.66  0.8883  5.236  3.232  8.3150  5.056
204  12.37  13.47  0.8567  5.204  2.960  3.9190  5.001
60   11.42  12.86  0.8683  5.008  2.850  2.7000  4.607
126  18.65  16.41  0.8698  6.285  3.594  4.3910  6.102
80   16.53  15.34  0.8823  5.875  3.467  5.5320  5.880
170  11.02  13.00  0.8189  5.325  2.701  6.7350  5.163
117  19.15  16.45  0.8890  6.245  3.815  3.0840  6.185
57   14.92  14.43  0.9006  5.384  3.412  1.1420  5.088
115  19.06  16.45  0.8854  6.416  3.719  2.2480  6.163
9    16.44  15.25  0.8880  5.884  3.505  1.9690  5.533
195  12.80  13.47  0.8860  5.160  3.126  4.8730  4.914
106  18.85  16.17  0.9056  6.152  3.806  2.8430  6.200

In [ ]:
len(X_test)

42

In [ ]:
predicted = model.predict(X_test) 
predicted

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2,
       1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 0, 1, 0, 2, 1])

# ทดสอบหาคำตอบ

In [ ]:
tt = np.array([[11.49,13.22,0.8263,5.304,2.695,5.388,5.31]])
df2 = pd.DataFrame(tt, columns = ['A', 'P', 'C', 'LK', 'WK', 'A_Coef', 'LKG'])
df2

A      P       C     LK     WK  A_Coef   LKG
0  11.49  13.22  0.8263  5.304  2.695   5.388  5.31

In [ ]:
type(df2)

pandas.core.frame.DataFrame

In [ ]:
predicted2 = model.predict(df2) 
predicted2

array([2])

In [ ]:
len(predicted2)

1

### Evaluating the KNeighborsClassifier

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [ ]:
y_test

78     1
65     0
94     1
22     0
63     0
46     0
96     1
11     0
2      0
155    2
24     0
101    1
95     1
74     1
114    1
160    2
99     1
82     1
84     1
108    1
169    2
162    2
85     1
188    2
116    1
150    2
193    2
133    1
98     1
168    2
207    2
204    2
60     0
126    1
80     1
170    2
117    1
57     0
115    1
9      0
195    2
106    1
Name: target, dtype: int64

In [ ]:
predicted

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2,
       1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 0, 1, 0, 2, 1])

In [ ]:
dx=pd.DataFrame({'acturl': y_test, 'predict': predicted})
#dx
#dx[dx.acturl != dx.predict]

In [ ]:
print(confusion_matrix(y_test, predicted))

[[ 9  0  1]
 [ 0 20  0]
 [ 0  0 12]]


In [ ]:
print(classification_report(y_test, predicted))

              precision    recall  f1-score   support

           0       1.00      0.90      0.95        10
           1       1.00      1.00      1.00        20
           2       0.92      1.00      0.96        12

    accuracy                           0.98        42
   macro avg       0.97      0.97      0.97        42
weighted avg       0.98      0.98      0.98        42

